# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vk_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vk_message.proto\x12\nvk_message\"-\n\tVkMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2K\n\tVkSerivce\x12>\n\x0ereceive_vk_msg\x12\x15.vk_message.VkMessage\x1a\x15.vk_message.VkMessageb\x06proto3')



_VKMESSAGE = DESCRIPTOR.message_types_by_name['VkMessage']
VkMessage = _reflection.GeneratedProtocolMessageType('VkMessage', (_message.Message,), {
  'DESCRIPTOR' : _VKMESSAGE,
  '__module__' : 'vk_message_pb2'
  # @@protoc_insertion_point(class_scope:vk_message.VkMessage)
  })
_sym_db.RegisterMessage(VkMessage)

_VKSERIVCE = DESCRIPTOR.services_by_name['VkSerivce']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VKMESSAGE._serialized_start=32
  _VKMESSAGE._serialized_end=77
  _VKSERIVCE._serialized_start=79
  _VKSERIVCE._serialized_end=154
# @@protoc_insertion_point(module_scope)
